#!/usr/bin/env bash
# A bash script that creates an RSA key pair
# Name of the created private key must be school
# Number of bits in the created key to created key must be 4096
# The created key must be protected by the passpharase "betty"
ssh-keygen -t rsa -b 4096 -P betty -f school